### PR TITLE
Add zremrangebyrank

### PR DESCRIPTION
**Pull request by penghap**
Add zremrangebyrank to limit useful information count

### CODE REVIEW

**Comment by noamshemesh** [comment]
Thanks @penghap 
On another thought, assuming we have an expiry for keys, don't you think the time of finding the indexes to delete isn't worth it?

**Comment by penghap** [comment]
Yes, in the limit times, I found redis record lots of request time, but
only the last few are useful. I think this can help us to reduce redis
storage.

Noam Shemesh <notifications@github.com> 于2019年3月2日周六 下午8:39写道：

**Comment by noamshemesh** [comment]
Please add a flag that is disabled by default for this.
A possible name for this property: “tidy”

**Comment by penghap** [comment]
Ok, I will do it, thanks.

Noam Shemesh <notifications@github.com> 于2019年3月2日周六 下午8:57写道：

> Please add a flag that is disabled by default for this.
> A possible name for this property: “tidy”
>

**Comment by penghap** [comment]
@noamshemesh  The tests have failed, seems to be the reason for the node version.

**Comment by noamshemesh** [comment]
That's fine, I'll drop support in node 4 and add the next versions. Thanks

**Comment by noamshemesh** [comment]
Merged. Thank you!

**Comment by Kikobeats** [comment]
Hello, I checked this PR in order to determinate the benefits to set `tidy=true` but I didn't find the point.

I understand that, since you are counting thing in redis, you don't want to count more than `max`, so you start deleting old counting over the same thing.

My question is: why not is this the default behavior? is it something related to perf? is it doesn't matter?

Just the thing I want to determinate is when I should use it 🙂

(after you reply I can do another PR for extend the explanation on docs)

**Comment by penghap** [comment]
Yes, if we clean up redundant data every time, It's will loss the perf. But when a los of records for a key in the redis, It will improve it. I just provides a choice. When and where use it, just depend on the actual situation 😄

**Comment by Kikobeats** [comment]
Thanks for the comment!

Are you using it in a real production environment?

How many records do you consider would be enough to be significant enable it?

**Comment by penghap** [comment]
Yes, I have already used. But in the service i need to limit the count.
I think the max records is enough.
It sounds interesting, but it may need another way to record the N.

**Pull request merged**
